version: '3'

services:
    nginx:
        restart: always
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - ${APP_PORT}:80
        depends_on:
            - app
        container_name: shop_nginx

    app:
        restart: always
        build:
            context: .
            dockerfile: ./_docker/app/DockerFile
        volumes:
            - ./:/var/www
        environment:
            - PHP_IDE_CONFIG=serverName=xdebug
        depends_on:
            - db
        container_name: shop_app

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8101:${DB_PORT}
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: shop_db

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - db
        container_name: shop_phpmyadmin

    redis:
        image: redis
        restart: always
        depends_on:
            - app
        ports:
            - 6379:${REDIS_PORT}
        volumes:
            - ../CacheData/data:/data
        container_name: shop_redis

    rabbitmq:
        restart: always
        image: rabbitmq:3.12.12-management
        depends_on:
            - app
        ports:
            - 5672:${RABBITMQ_PORT}
            - 15672:${RABBITMQ_ADMIN_PORT}
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        container_name: shop_rabbitmq
